name: rainy_pay
description: Simple Rainy Pay wallet (USDT-BEP20, Polygon, LTC UI only)
version: 0.9.0

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  clipboard: ^0.1.3

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
