name: rainy_pay
description: Simple Rainy Pay wallet (USDT-BEP20, Polygon, LTC)
version: 0.9.0

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web3: ^1.3.0
  litecoin_dart: ^0.1.0
  clipboard: ^0.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
